/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as ImageIdRouteImport } from './routes/image.$id'
import { Route as AudioIdRouteImport } from './routes/audio.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageIdRoute = ImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIdRoute = AudioIdRouteImport.update({
  id: '/audio/$id',
  path: '/audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/audio/$id': typeof AudioIdRoute
  '/image/$id': typeof ImageIdRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/audio/$id': typeof AudioIdRoute
  '/image/$id': typeof ImageIdRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/audio/$id': typeof AudioIdRoute
  '/image/$id': typeof ImageIdRoute
  '/video/$id': typeof VideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/audio/$id' | '/image/$id' | '/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/audio/$id' | '/image/$id' | '/video/$id'
  id: '__root__' | '/' | '/search' | '/audio/$id' | '/image/$id' | '/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AudioIdRoute: typeof AudioIdRoute
  ImageIdRoute: typeof ImageIdRoute
  VideoIdRoute: typeof VideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/$id': {
      id: '/image/$id'
      path: '/image/$id'
      fullPath: '/image/$id'
      preLoaderRoute: typeof ImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/$id': {
      id: '/audio/$id'
      path: '/audio/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof AudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AudioIdRoute: AudioIdRoute,
  ImageIdRoute: ImageIdRoute,
  VideoIdRoute: VideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
